### ISSUE TITLE
About the model

### ISSUE THREAD

**Issue by cjlala** [dlarionov/1c#1]
Hi bro. Thanks for your contribution. But could you share you latest idea? I struggle in the tuning, having no idea how to tune a good model, for that the original xgb result is better than the tuned xgb results in the LB.

**Comment by dlarionov** [comment]
hi, I am still on the essembling phase. For now I have alot of separeted kaggle notebooks. In the end I will copy them to this repo.

My ideas about features did not change and it gives 0.9106 with a single xgb model.
